### ISSUE TITLE
PerformanceCounter for CPU and RAM

### ISSUE THREAD

**Issue by KP0H** [Rankcore/Orationi#27]
Our slaves and modules should collect performance and provide information to master in future.
At current stage suggest start with simple counters.
I think it's should be part of ModuleCore.

**Comment by pastukhoff** [comment]
I think, I will make ISimpleCounter interface and will add two counter classes for CPU and RAM in Diagnostic.ModuleCore

**Comment by KP0H** [comment]
@pastukhoff i think you may do this issue somehow. It's does now realy important  now. Main challenge  of current stage - prepare something usefull. We improve all someday.
And use please https://waffle.io/Rankcore/Orationi to manage issue stage.
