### ISSUE TITLE
Upload module via Manager

### ISSUE THREAD

**Issue by KP0H** [Rankcore/Orationi#30]
Also create new custom module

**Comment by kirill-kruchkov** [comment]
@KP0H can you provide me with sample module to upload?

**Comment by KP0H** [comment]
@kirill-kruchkov just use random zip archive to tests. Sample module not ready yet.

**Comment by kirill-kruchkov** [comment]
Looks like this. Pretty straitforward.
![2016-02-21 16 01 39](https://cloud.githubusercontent.com/assets/1702672/13202694/814bd4e4-d8b4-11e5-8ae1-b29b94763c03.png)
