### ISSUE TITLE
[Slave] should provide system information

### ISSUE THREAD

**Issue by KP0H** [Rankcore/Orationi#57]
We should have all information about slave system. 
List of attributes for example:
Operationg System 
Version (Build)
Type (x86, x64)
CPU (full information include vendor, model, etc)
TimeZone
Disks
Avaliable disk spaces
RAM
Network adapters
Video Card (full information)

this list should be expanding...

**Comment by KP0H** [comment]
@pastukhoff i suggest start work on it in slave project and then we will have full visuion to add master project same task  and describe contacts and interfaces.
Could you please begin it?

**Comment by pastukhoff** [comment]
@KP0H Yes, boss.

**Comment by KP0H** [comment]
https://github.com/Orationi/Slave/issues/3
