### ISSUE TITLE
[Manager] Add some UI to Manager

### ISSUE THREAD

**Issue by kirill-kruchkov** [Rankcore/Orationi#63]

**Comment by kirill-kruchkov** [comment]
We have chosen Material UI (http://www.material-ui.com/#/get-started/prerequisites) for UI. If it won't fit our requirements we'll switch to Elemental UI (http://elemental-ui.com/css). 
Fusioncharts (http://www.fusioncharts.com/reactjs-charts/#/demos/ex4) look good for charts.

**Comment by KP0H** [comment]
https://github.com/Orationi/Manager/issues/1
