### ISSUE TITLE
[Master] API - Provide correct HTTP statuses for errors

### ISSUE THREAD

**Issue by kirill-kruchkov** [Rankcore/Orationi#78]
500 - unexpected error
400 - bad request
404 - not found (e.g. if module is not found when uploading new module version)
... and so on

**Comment by KP0H** [comment]
@kirill-kruchkov could you please check and close issue?

**Comment by kirill-kruchkov** [comment]
@KP0H sure, taking the issue

**Comment by KP0H** [comment]
https://github.com/Orationi/Master/issues/6
